p2m-message-server:
  server:
    path: SERVER_PATH
    interval: CHECK_INTERVAL

  database:
    host: DB_HOST
    username: DB_USERNAME
    password: DB_PASSWORD
    database: DB_DATABASE

  jpush:
    appKey: JPUSH_APPKEY
    masterSecret: JPUSH_MASTER
